use_frameworks!

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'FoodTrackerModel_Example' do
  pod 'FoodTrackerModel', :path => '../'

  target 'FoodTrackerModel_Tests' do
    inherit! :search_paths

    
  end
end
